### ISSUE TITLE
Not all stocks in Data Set Been Processed

### ISSUE THREAD

**Issue by joeleen2016** [okomarov/metastockread#1]
HI,

When I run the code on the sample code provided it does not process all the stocks. It processes up to number 255. In the metastock file structure the first 255 stocks have an extension of .DAT and the remainder an extension of .MWD, so I think something is happening here. I have run the code on my own data, which contains 497 stocks and same issue (Files Should Be Attached). 

Can this please be looked at or am I missing something in implementing the code

Thank you,

Joe

**Comment by okomarov** [comment]
Hi @joeleen2016, thanks for reporting. 

It is a limitation of older versions of Metastock, that could only store max 255 files in a folder, and hence the emaster and master files would index only the .dat files. You will need the xmaster file to index the .mwd.

Source: http://www.stockblocks.com/support/metastock/xmaster.htm

**Comment by okomarov** [comment]
I'll be closing but feel to reopen if that does not solve your issue.

**Comment by joeleen2016** [comment]
Hi, 

I found an issue with the output. The Stock Name is not been matched to it's corressponding data.

See the attached. I run the metastockread code on Metastock Data Master File containing 10 securities. See "10 Stocks - Master File.JPG". If I open the data for the stock 'AINC.K' - 'ASHFORD ORD' (Field Number 10) you get "AINC.K - ASHFORD ORD - METASTOCK M FILE CONVERSION.JPG."

You'll see the Open is 1.220, the High is 1.2390, the Low is 1.1800 and the Close is 1.1800.

If you check the NASDAQ Listing, see "NASDAQ - AINK.K.JPG" that the Close was 46.60, the High was 47.59 and the Low was 46.60.

Now if I open Field Number Two's Data - ABE - ABERDEEN  EMERGIN.JPG" you'll see the Open is 46.93, the High is 47.59, the Low is 46.60 and the Close is 46.60. (The correct data for AINC.K ASHFORD ORD).

Also I have another converter and ran it on the same data, See "AINC.K - Premium Converter.JPG." This gives the same data as reported by NASDAQ and also is the same as the metastockread data for ABE - ABERDEEN  EMERGIN.

So Stock Names are been mixed up somehow.

I would attach the raw data but I can't attach the file types through this interface.

Regards,

Joseph








![nasdaq - ainc k](https://cloud.githubusercontent.com/assets/20351106/18422567/da1c553c-7894-11e6-9cb4-afe340bde794.JPG)
![10 stocks - master file](https://cloud.githubusercontent.com/assets/20351106/18422565/da1a4a4e-7894-11e6-987a-501186190cfd.JPG)
![abe - aberdeen erergin - metastock m file conversion](https://cloud.githubusercontent.com/assets/20351106/18422564/da18935c-7894-11e6-9503-3f429969b030.JPG)
![ainc k - ashford ord - metastock m file conversion](https://cloud.githubusercontent.com/assets/20351106/18422566/da1b360c-7894-11e6-852b-fec265d79bbe.JPG)
![ainc k - premium converter](https://cloud.githubusercontent.com/assets/20351106/18422568/da1da66c-7894-11e6-81f2-26f6ef21a0c3.JPG)

**Comment by okomarov** [comment]
Hi Joseph, 
Can you upload the data to some service like Dropbox and post the link here? 

I can't debug without actual data.
