### ISSUE TITLE
Stock Names Mix Up

### ISSUE THREAD

**Issue by joeleen2016** [okomarov/metastockread#2]
Hi,

I found an issue with the output. The Stock Name is not been matched to it's corressponding data.

See the attached. I run the metastockread code on Metastock Data Master File containing 10 securities. See "10 Stocks - Master File.JPG". If I open the data for the stock 'AINC.K' - 'ASHFORD ORD' (Field Number 10) you get "AINC.K - ASHFORD ORD - METASTOCK M FILE CONVERSION.JPG."

You'll see the Open is 1.220, the High is 1.2390, the Low is 1.1800 and the Close is 1.1800.

If you check the NASDAQ Listing, see "NASDAQ - AINK.K.JPG" that the Close was 46.60, the High was 47.59 and the Low was 46.60.

Now if I open Field Number Two's Data - ABE - ABERDEEN EMERGIN.JPG" you'll see the Open is 46.93, the High is 47.59, the Low is 46.60 and the Close is 46.60. (The correct data for AINC.K ASHFORD ORD).

Also I have another converter and ran it on the same data, See "AINC.K - Premium Converter.JPG." This gives the same data as reported by NASDAQ and also is the same as the metastockread data for ABE - ABERDEEN EMERGIN.

So Stock Names are been mixed up somehow.

I would attach the raw data but I can't attach the file types through this interface.

Regards,

Joseph
![nasdaq - ainc k](https://cloud.githubusercontent.com/assets/20351106/18422842/65410d54-7897-11e6-9bca-8c5cac38c107.JPG)
![10 stocks - master file](https://cloud.githubusercontent.com/assets/20351106/18422841/653bdc76-7897-11e6-81fa-c34a28d47dd0.JPG)
![abe - aberdeen emergin - metastock m file conversion](https://cloud.githubusercontent.com/assets/20351106/18422843/654221bc-7897-11e6-9d01-8872aaa58950.JPG)
![ainc k - ashford ord - metastock m file conversion](https://cloud.githubusercontent.com/assets/20351106/18422844/654500e4-7897-11e6-9c0e-7032bbfc0ab5.JPG)
![ainc k - premium converter](https://cloud.githubusercontent.com/assets/20351106/18422845/65453082-7897-11e6-8433-3563098d15a9.JPG)

**Comment by okomarov** [comment]
@joeleen2016 

Hi Joseph,
Can you upload the data to some service like Dropbox and post the link here?

I can't debug without actual data.

**Comment by joeleen2016** [comment]
Hi,

Please try this link:

http://expirebox.com/download/fdbcbe9c1495e3ac93a4af78c0e3dbc4.html

Meta_Test.rar

Regards,

Joseph

**Comment by okomarov** [comment]
@joeleen2016 With previous changes, I had introduced a regression in the ordering of the data files. This should be fixed now. Thanks for reporting the issue and thoroughly documenting it.
