### ISSUE TITLE
EMASTER & MASTER Output Error

### ISSUE THREAD

**Issue by joeleen2016** [okomarov/metastockread#3]
Hi,

When I run the code on the EMASTER and MASTER files I get an error and no data output.

> In metastockread (line 124) 
> Warning: The following error was caught while executing 'onCleanup' class destructor:
> Invalid file identifier. Use fopen to generate a valid file identifier. 

I do get a data output when I run on the XMASTER file.

I've attached the raw data to the following download link:

http://expirebox.com/download/a0d58ac48a5b16af739e099a3a2f70df.html

See the three images below, for the output from Matlab for the EMASTER, MASTER and XMASTER files.

Regards,

Joe

![xmaster](https://cloud.githubusercontent.com/assets/20351106/18616045/ea1a638a-7dac-11e6-8769-03572631648b.JPG)
![emaster](https://cloud.githubusercontent.com/assets/20351106/18616046/ea1ba312-7dac-11e6-81be-c67b60be06bc.JPG)
![master](https://cloud.githubusercontent.com/assets/20351106/18616047/ea1d75b6-7dac-11e6-86bc-3689196ef194.JPG)

**Comment by okomarov** [comment]
Hi thanks for the report, could you please provide the steps to reproduce the error?

**Comment by joeleen2016** [comment]
1) Run metastockread.m
2) "Load metastock file" explorer window opens. Browse to "Joe_Data" Folder
3) Select "EMASTER", "MASTER" or "XMASTER"

Raw Metastock Files available at:

http://expirebox.com/download/a0d58ac48a5b16af739e099a3a2f70df.html

**Comment by okomarov** [comment]
@joeleen2016 Try now, it should not warn anymore.

**Comment by joeleen2016** [comment]
Brilliant ! Thank you !

**Comment by okomarov** [comment]
@joeleen2016 Thanks again for taking the time to report the issue, very appreciated.
