### ISSUE TITLE
short vs. long names within *master files?

### ISSUE THREAD

**Issue by Brad-Stiritz** [okomarov/metastockread#4]
Hi Oleg,

Thank you for creating and posting this function, it's very appreciated. I'm using your utility to read the [Norgate Premium](https://www.premiumdata.net/) Database, which uses the Metastock file format. I noticed that your read*Master functions are often returning truncated values for the 'name' field. It appears that those functions are hard-coded to look for a 16-character wide field.

I touched base with Norgate tech. support on this. The rep suggested that you may have coded metastockread to an older version of the Metastock format, which only provides for a 16-character name field. There is apparently a newer version of the standard, which also includes a 45-character name field. Please see attached screen snip and emaster file below.

The snip shows the provided emaster file, opened in a programming editor. As you can see, there are 2 names stored internally per symbol. For example:

S&P 1500 Aerospa
S&P 1500 Aerospace & Defense SubInd

May I ask for your assistance please, to read the longer name? I understand that you may not wish to modify your release code to handle the additional complexity. In this case, do you have a suggestion please, how to modify the relevant line to read the longer name? For example, in readXmaster on line 11:

names      = cellfun(@(x) char(x(1:find(x == 0,1,'first'))), num2cell(tmp(17:39,:).',2),'un',0) ;

I have to admit, I don't understand the math here. (How are 16 characters being read? 17 + 16 - 1 = 33)

Please let me know your thoughts?
Thanks,
Brad

2 Files attached:
![norgate emaster - 2 name fields](https://user-images.githubusercontent.com/3894205/29975225-338e866c-8efb-11e7-8a5c-dfc1625c1ee2.png)

[emaster.zip](https://github.com/okomarov/metastockread/files/1270620/emaster.zip)

**Comment by okomarov** [comment]
@Brad-Stiritz I pushed the change, thanks for reporting

**Comment by Brad-Stiritz** [comment]
Thank you for the quick update, I appreciate your help with this. I'm sorry not to have been thinking ahead, and for the inconvenience: would you mind please taking a look at the master and xmaster file formats as well? Please see attached examples from the same folder as the emaster above.

Also, would you mind please updating the change log at the top of the file, to indicate the present modifications? This will be helpful in keeping track of your latest code version.

[(x)master.zip](https://github.com/okomarov/metastockread/files/1270973/x.master.zip)

**Comment by okomarov** [comment]
@Brad-Stiritz checked the other master files, they do not have a long name there. 
With respect the log, I have not been using it for a while. Usually, with git you keep track with release tags, but this is a very small contribution and not really worth the effort. I guess just download the most recent release from the master branch.
