### ISSUE TITLE
Please modify readMaster and readXmaster, per recent readEmaster change?

### ISSUE THREAD

**Issue by Brad-Stiritz** [okomarov/metastockread#5]
Hi Oleg,

Apologies for the confusion here. The readMaster and readXmaster functions also need to be modified as well, please. Would you mind please making changes in those two functions, so that the 'fullname' field also appears in master and xmaster? (Just like it appears now in emaster)

The goal is to be able to see 'fullname' in all 3 file types, please : master, emaster, xmaster. I have attached a zip with all three, from the same data folder.

Thanks,
Brad

[master-emaster-xmaster.zip](https://github.com/okomarov/metastockread/files/1278789/master-emaster-xmaster.zip)

**Comment by Brad-Stiritz** [comment]
In case anyone else is interested in this, I was able to figure out the needed change in readXmaster --

```
% Select and convert useful info
Out = struct('datNum', num2cell(typecast(reshape(tmp(66:67,:),[],1),'uint16'))              ,...
             'symbol', cellstr(char(tmp(2:15,:).'))                                         ,...
             'name'  , names                                                                ,...
             'inDate', fmtStrDate(obj,single(typecast(reshape(tmp(109:112,:),[],1),'uint32')))  ,...
             'fiDate', fmtStrDate(obj,single(typecast(reshape(tmp(117:120,:),[],1),'uint32')))  ,...
             'freq'  , cellstr(char(tmp(63,:).'))                                           ,...
             'idFreq', num2cell(tmp(65,:).')                                               ,...
             'fullname', cellstr(char(tmp(17:62,:)).'));    

```

I don't need readMaster, so I didn't investigate there. Here's the basic idea : (tmp) is a per-column array. Step through the code, and look at (tmp) in the Variables window. The (fullname) value will be a longish vertical series of digits, bracketed by (0). Determine the index range via trial and error.

Oleg, it would be still be appreciated if you could complete this update on the remaining sub-functions, please?

Thanks,
Brad

**Comment by okomarov** [comment]
@Brad-Stiritz Thanks for the contribution! The master file does not seem to have a fullname. I pushed the change

**Comment by Brad-Stiritz** [comment]
You're welcome, glad to help out. 

By the way, I'm working on a significant framework based on this code of yours. If the project is successful, I'm considering sharing on GitHub. In that case, I'll update you in the next month or so.
